const SUPABASE_URL = 'https://airmjmjdrswqkgdbgind.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFpcm1qbWpkcnN3cWtnZGJnaW5kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODI2MTMwOTQsImV4cCI6MjA5ODE4OTA5NH0.8uesJ31Btb5A17tAJCKi5d0O3nMOSlVPwquVc25Ktb4';
const sb = supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);
let session=null, user=null, family=null, cadastros=[], movs=[];
const $=id=>document.getElementById(id);
const today=()=>new Date().toISOString().slice(0,10);
const money=v=>(Number(v)||0).toLocaleString('pt-BR',{style:'currency',currency:'BRL'});
const code=()=>Math.random().toString(36).slice(2,8).toUpperCase();
function show(id){['authView','setupView','appView'].forEach(x=>$(x).classList.toggle('hidden',x!==id)); $('btnLogout').classList.toggle('hidden',id==='authView');}
function msg(id,t){$(id).textContent=t||''}
async function init(){ $('movLancamento').value=today(); $('movVencimento').value=today(); bind(); const res=await sb.auth.getSession(); session=res.data.session; user=session?.user||null; await route(); }
async function route(){ if(!user){show('authView');return;} family=await getFamily(); if(!family){show('setupView');return;} show('appView'); await loadAll(); }
async function getFamily(){ const {data,error}=await sb.from('bevi_configuracoes').select('*').eq('chave','familia_ativa').maybeSingle(); if(error){console.warn(error);return null;} return data?.valor||null; }
async function setFamily(fam){ const {error}=await sb.from('bevi_configuracoes').upsert({familia:'bevi',chave:'familia_ativa',valor:fam},{onConflict:'familia,chave'}); if(error) throw error; family=fam; }
async function loadAll(){ $('familyTitle').textContent=family.nome; $('familyCode').textContent=family.codigo; $('userTitle').textContent=user.email; await Promise.all([loadCadastros(),loadMovs()]); renderDashboard(); renderCadastros(); renderSelects(); renderMovs(); }
async function loadCadastros(){ const {data,error}=await sb.from('bevi_cadastros').select('*').eq('familia','bevi').order('ativo',{ascending:false}).order('nome',{ascending:true}); if(error) throw error; cadastros=data||[]; }
async function loadMovs(){ const {data,error}=await sb.from('bevi_movimentacoes').select('*').eq('familia','bevi').order('data_vencimento',{ascending:false}).order('criado_em',{ascending:false}); if(error) throw error; movs=data||[]; }
function byTipo(t){return cadastros.filter(c=>c.tipo===t && c.ativo).sort((a,b)=>a.nome.localeCompare(b.nome,'pt-BR'));}
function fill(sel, arr, blank='Selecione'){ sel.innerHTML=`<option value="">${blank}</option>`+arr.map(x=>`<option>${x.nome}</option>`).join('');}
function renderSelects(){ fill($('movResponsavel'), byTipo('pessoa'),'Casa/Larissa/Davi'); $('movResponsavel').insertAdjacentHTML('afterbegin','<option>Casa</option>'); fill($('movPagador'), byTipo('pessoa'),'Quem pagou/recebeu'); fill($('movCategoria'), byTipo('categoria'),'Categoria'); fill($('movTerceiro'), byTipo('terceiro'),'Sem terceiro'); }
function renderDashboard(){ const confirmed=['pago','recebido','confirmado']; const rec=movs.filter(m=>m.modulo==='receita'&&confirmed.includes(m.status)).reduce((s,m)=>s+Number(m.valor),0); const desp=movs.filter(m=>m.modulo==='despesa'&&confirmed.includes(m.status)).reduce((s,m)=>s+Number(m.valor),0); const pend=movs.filter(m=>m.status==='pendente').reduce((s,m)=>s+Number(m.valor),0); $('mReceitas').textContent=money(rec); $('mDespesas').textContent=money(desp); $('mSaldo').textContent=money(rec-desp); $('mPendencias').textContent=money(pend); }
function renderMovs(){ const mod=$('filterModulo').value, st=$('filterStatus').value; const rows=movs.filter(m=>(!mod||m.modulo===mod)&&(!st||m.status===st)); $('movList').innerHTML=''; if(!rows.length){$('movList').innerHTML='<p class="muted">Nenhuma movimentação encontrada.</p>'; return;} rows.forEach(m=>{ const el=$('movTpl').content.cloneNode(true); el.querySelector('.title').textContent=m.titulo; el.querySelector('.meta').textContent=`${m.modulo} • ${m.status} • Resp: ${m.responsavel||'-'} • Pg/Rec: ${m.pagador||'-'} • Venc: ${m.data_vencimento||'-'} • Pag/Rec: ${m.data_pagamento||'-'}`; el.querySelector('.valor').textContent=money(m.valor); el.querySelector('.pay').onclick=()=>baixar(m); el.querySelector('.edit').onclick=()=>editar(m); el.querySelector('.del').onclick=()=>excluir(m); $('movList').appendChild(el); }); }
function renderCadastros(){ $('cadList').innerHTML=''; cadastros.forEach(c=>{ const div=document.createElement('div'); div.className='item'; div.innerHTML=`<div><strong>${c.nome}</strong><p class="meta">${c.tipo} • ${c.ativo?'Ativo':'Inativo'}</p></div><button class="small secondary">${c.ativo?'Inativar':'Ativar'}</button>`; div.querySelector('button').onclick=async()=>{ await sb.from('bevi_cadastros').update({ativo:!c.ativo}).eq('id',c.id); await loadAll();}; $('cadList').appendChild(div); }); }
async function salvarMov(){ const payload={familia:'bevi',modulo:$('movModulo').value,tipo:$('movTipo').value,titulo:$('movTitulo').value.trim(),valor:Number($('movValor').value||0),responsavel:$('movResponsavel').value,pagador:$('movPagador').value,terceiro:$('movTerceiro').value,categoria:$('movCategoria').value,status:$('movStatus').value,data_lancamento:$('movLancamento').value||today(),data_vencimento:$('movVencimento').value||null,data_pagamento:$('movPagamento').value||null,cartao:$('movCartao').value||null,parcela_atual:$('movParcelaAtual').value?Number($('movParcelaAtual').value):null,parcelas_total:$('movParcelasTotal').value?Number($('movParcelasTotal').value):null,observacao:$('movObs').value||null,dados:{usuario:user.email}}; if(!payload.titulo||!payload.valor){msg('movMsg','Informe título e valor.'); return;} const {error}=await sb.from('bevi_movimentacoes').insert(payload); if(error){msg('movMsg',error.message);return;} msg('movMsg','Lançamento salvo.'); ['movTitulo','movValor','movCartao','movParcelaAtual','movParcelasTotal','movObs'].forEach(id=>$(id).value=''); await loadAll(); }
async function baixar(m){ const status=m.modulo==='receita'?'recebido':'pago'; const {error}=await sb.from('bevi_movimentacoes').update({status,data_pagamento:today(),atualizado_em:new Date().toISOString()}).eq('id',m.id); if(error) alert(error.message); await loadAll(); }
async function editar(m){ const novo=prompt('Novo valor:',m.valor); if(novo===null) return; const novoStatus=prompt('Novo status:',m.status)||m.status; const {error}=await sb.from('bevi_movimentacoes').update({valor:Number(novo),status:novoStatus,atualizado_em:new Date().toISOString()}).eq('id',m.id); if(error) alert(error.message); await loadAll(); }
async function excluir(m){ if(!confirm('Excluir este lançamento?')) return; const {error}=await sb.from('bevi_movimentacoes').delete().eq('id',m.id); if(error) alert(error.message); await loadAll(); }
async function salvarCad(){ const tipo=$('cadTipo').value,nome=$('cadNome').value.trim(); if(!nome)return; const {error}=await sb.from('bevi_cadastros').insert({familia:'bevi',tipo,nome}); if(error){alert(error.message);return;} $('cadNome').value=''; await loadAll(); }
function exportCsv(){ const cols=['id','modulo','tipo','titulo','responsavel','pagador','terceiro','categoria','valor','status','data_lancamento','data_vencimento','data_pagamento','cartao','parcela_atual','parcelas_total','observacao']; const csv=[cols.join(';')].concat(movs.map(r=>cols.map(c=>`"${String(r[c]??'').replaceAll('"','""')}"`).join(';'))).join('\n'); const blob=new Blob([csv],{type:'text/csv;charset=utf-8'}); const a=document.createElement('a'); a.href=URL.createObjectURL(blob); a.download='bevi_movimentacoes.csv'; a.click(); }
function bind(){ $('btnSignup').onclick=async()=>{ msg('authMsg','Criando conta...'); const {data,error}=await sb.auth.signUp({email:$('authEmail').value,password:$('authPassword').value,options:{data:{name:$('authName').value}}}); if(error){msg('authMsg',error.message);return;} user=data.user; msg('authMsg','Conta criada. Se pedir confirmação por e-mail, confirme antes de entrar.'); await route();}; $('btnLogin').onclick=async()=>{ const {data,error}=await sb.auth.signInWithPassword({email:$('authEmail').value,password:$('authPassword').value}); if(error){msg('authMsg',error.message);return;} session=data.session; user=data.user; await route();}; $('btnLogout').onclick=async()=>{await sb.auth.signOut(); user=null; family=null; show('authView');}; $('btnCreateFamily').onclick=async()=>{try{ await setFamily({nome:$('familyName').value||'BEVI Casa',codigo:code(),criado_por:user.email}); await route();}catch(e){msg('setupMsg',e.message)}}; $('btnJoinFamily').onclick=async()=>{ msg('setupMsg','Nesta versão MVP, use o mesmo código após a primeira pessoa criar. Como o banco é pessoal, o vínculo será único para vocês dois.'); const fam={nome:'BEVI Casa',codigo:$('inviteCode').value||'BEVI',criado_por:user.email}; await setFamily(fam); await route();}; $('btnCopyCode').onclick=()=>navigator.clipboard.writeText($('familyCode').textContent); document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active')); b.classList.add('active'); document.querySelectorAll('.tabpane').forEach(p=>p.classList.add('hidden')); $('tab-'+b.dataset.tab).classList.remove('hidden');}); $('btnSalvarMov').onclick=salvarMov; $('btnSalvarCad').onclick=salvarCad; $('btnRecarregar').onclick=loadAll; $('filterModulo').onchange=renderMovs; $('filterStatus').onchange=renderMovs; $('btnExportCsv').onclick=exportCsv; }
init();
